'use client';

import { useEffect, useMemo, useState } from 'react';
import styles from './operations-console.module.css';

type Row=Record<string,any>;
async function api(path:string,method='GET',body?:unknown){const r=await fetch(`/api/control-plane${path}`,{method,headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error?.message||`HTTP ${r.status}`);return p?.data??p}

export function TicketsConsole(){
 const [tickets,setTickets]=useState<Row[]>([]),[merchants,setMerchants]=useState<Row[]>([]),[stores,setStores]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[users,setUsers]=useState<Row[]>([]);
 const [selected,setSelected]=useState(''),[detail,setDetail]=useState<any>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{ok:boolean;text:string}|null>(null);
 const [filter,setFilter]=useState({status:'',priority:'',search:''});
 const [create,setCreate]=useState({merchantId:'',storeId:'',serviceOrderId:'',category:'SUPPORT',subject:'',description:'',priority:'NORMAL',assignedToUserId:''});
 const [edit,setEdit]=useState({status:'IN_PROGRESS',priority:'NORMAL',assignedToUserId:''}); const [message,setMessage]=useState(''); const [internal,setInternal]=useState(false);
 const merchantStores=useMemo(()=>stores.filter(s=>!create.merchantId||s.merchant_id===create.merchantId),[stores,create.merchantId]);
 const merchantOrders=useMemo(()=>orders.filter(o=>!create.merchantId||o.merchant_id===create.merchantId),[orders,create.merchantId]);
 async function refresh(){try{const q=new URLSearchParams();if(filter.status)q.set('status',filter.status);if(filter.priority)q.set('priority',filter.priority);if(filter.search)q.set('search',filter.search);const [t,m,s,o,u]=await Promise.all([api(`/tickets?${q}`),api('/merchants?limit=200'),api('/stores?limit=300'),api('/expert/orders?limit=300'),api('/users')]);setTickets(t.tickets||[]);setMerchants(m.merchants||[]);setStores(s.stores||[]);setOrders(o.orders||[]);setUsers(u.users||[]);}catch(e:any){setNotice({ok:false,text:e.message})}}
 useEffect(()=>{void refresh()},[]);
 async function load(id:string){setSelected(id);if(!id){setDetail(null);return}try{const d=await api(`/tickets/${id}`);setDetail(d);const t=d.ticket||{};setEdit({status:String(t.status||'IN_PROGRESS'),priority:String(t.priority||'NORMAL'),assignedToUserId:String(t.assigned_to_user_id||'')});}catch(e:any){setNotice({ok:false,text:e.message})}}
 async function run(label:string,fn:()=>Promise<any>){setBusy(true);setNotice(null);try{await fn();setNotice({ok:true,text:`${label}: concluído.`});await refresh();if(selected)await load(selected);}catch(e:any){setNotice({ok:false,text:`${label}: ${e.message}`})}finally{setBusy(false)}}
 return <div className={styles.wrap}>
  <div className={styles.hero}><div><h1>Tickets & Support</h1><p>Atendimento unificado de suporte, operação e contratação XPay.Expert, ligado a Merchant, Store e ServiceOrder.</p></div><span className={styles.live}>SERVICE DESK</span></div>
  {notice?<div className={`${styles.notice} ${notice.ok?styles.ok:styles.bad}`}>{notice.text}</div>:null}
  <div className={styles.grid}>
   <section className={styles.card}><h2>Novo ticket</h2><p>O ticket pode nascer como suporte geral ou associado diretamente a uma contratação Expert.</p><div className={styles.form}>
    <Select label="Merchant" value={create.merchantId} onChange={v=>setCreate({...create,merchantId:v,storeId:'',serviceOrderId:''})} options={merchants.map(x=>[x.id,`${x.name} · ${x.email}`])}/>
    <div className={styles.row}><Select label="Store" value={create.storeId} onChange={v=>setCreate({...create,storeId:v})} options={merchantStores.map(x=>[x.id,`${x.store_code} · ${x.name}`])}/><Select label="XPay Order" value={create.serviceOrderId} onChange={v=>setCreate({...create,serviceOrderId:v,category:v?'XPAY_EXPERT':create.category})} options={merchantOrders.map(x=>[x.id,`${x.order_code} · ${x.offering_name}`])}/></div>
    <div className={styles.row}><Select label="Categoria" value={create.category} onChange={v=>setCreate({...create,category:v})} options={['SUPPORT','TECHNICAL','PAYMENTS','PAYOUT','PROCESSING','XPAY_EXPERT','COMMERCIAL','OTHER'].map(x=>[x,x])}/><Select label="Prioridade" value={create.priority} onChange={v=>setCreate({...create,priority:v})} options={['LOW','NORMAL','HIGH','URGENT'].map(x=>[x,x])}/></div>
    <Input label="Assunto" value={create.subject} onChange={v=>setCreate({...create,subject:v})}/><Textarea label="Descrição" value={create.description} onChange={v=>setCreate({...create,description:v})}/><Select label="Responsável" value={create.assignedToUserId} onChange={v=>setCreate({...create,assignedToUserId:v})} options={users.filter(x=>x.status==='active').map(x=>[x.id,`${x.name} · ${x.role}`])}/>
    <button disabled={busy||!create.subject} className={styles.primary} onClick={()=>run('Criar ticket',async()=>{const d=await api('/tickets','POST',{...create,merchantId:create.merchantId||null,storeId:create.storeId||null,serviceOrderId:create.serviceOrderId||null,assignedToUserId:create.assignedToUserId||null});setCreate({...create,subject:'',description:''});if(d.ticket?.id)await load(d.ticket.id)})}>Criar ticket</button>
   </div></section>
   <section className={styles.card}><h2>Fila</h2><p>Prioridade e estado operacional da equipa.</p><div className={styles.form}><div className={styles.row}><Select label="Status" value={filter.status} onChange={v=>setFilter({...filter,status:v})} options={['OPEN','IN_PROGRESS','WAITING_CUSTOMER','WAITING_INTERNAL','RESOLVED','CLOSED'].map(x=>[x,x])}/><Select label="Prioridade" value={filter.priority} onChange={v=>setFilter({...filter,priority:v})} options={['LOW','NORMAL','HIGH','URGENT'].map(x=>[x,x])}/></div><Input label="Pesquisa" value={filter.search} onChange={v=>setFilter({...filter,search:v})}/><button className={styles.secondary} onClick={()=>void refresh()}>Aplicar filtros</button><Select label={`Tickets (${tickets.length})`} value={selected} onChange={v=>void load(v)} options={tickets.map(x=>[x.id,`${x.priority} · ${x.ticket_code} · ${x.subject} · ${x.status}`])}/></div></section>
   <section className={styles.card}><h2>Gestão do ticket</h2><p>Estado, prioridade e responsável ficam auditáveis no backend.</p>{detail?<div className={styles.form}><div className={styles.notice}>{detail.ticket?.ticket_code}\n{detail.ticket?.subject}\nMerchant: {detail.ticket?.merchant_name||'—'}\nStore: {detail.ticket?.store_name||'—'}\nXPay: {detail.ticket?.order_code||'—'}</div><div className={styles.row}><Select label="Status" value={edit.status} onChange={v=>setEdit({...edit,status:v})} options={['OPEN','IN_PROGRESS','WAITING_CUSTOMER','WAITING_INTERNAL','RESOLVED','CLOSED'].map(x=>[x,x])}/><Select label="Prioridade" value={edit.priority} onChange={v=>setEdit({...edit,priority:v})} options={['LOW','NORMAL','HIGH','URGENT'].map(x=>[x,x])}/></div><Select label="Responsável" value={edit.assignedToUserId} onChange={v=>setEdit({...edit,assignedToUserId:v})} options={users.filter(x=>x.status==='active').map(x=>[x.id,`${x.name} · ${x.role}`])}/><div className={styles.actions}><button disabled={busy} className={styles.primary} onClick={()=>run('Atualizar ticket',()=>api(`/tickets/${selected}`,'PATCH',{...edit,assignedToUserId:edit.assignedToUserId||null}))}>Guardar</button><button disabled={busy} className={styles.danger} onClick={()=>confirm('Apagar este ticket e as mensagens?')&&run('Apagar ticket',async()=>{await api(`/tickets/${selected}`,'DELETE');setSelected('');setDetail(null)})}>Apagar ticket</button></div></div>:<div className={styles.meta}>Selecione um ticket.</div>}</section>
   <section className={styles.card}><h2>Mensagens & notas</h2><p>Notas internas não são destinadas ao Merchant; mensagens normais podem ser usadas na futura caixa Merchant.</p>{detail?<div className={styles.form}><div className={styles.notice}>{(detail.messages||[]).map((m:Row)=>`${new Date(m.created_at).toLocaleString()} · ${m.internal?'INTERNO':'MENSAGEM'} · ${m.control_plane_user_name||m.merchant_name||m.author_type}\n${m.body}`).join('\n\n')||'Sem mensagens.'}</div><Textarea label="Nova mensagem" value={message} onChange={setMessage}/><label className={styles.meta}><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Nota interna</label><button disabled={busy||!message.trim()} className={styles.primary} onClick={()=>run('Adicionar mensagem',async()=>{await api(`/tickets/${selected}/messages`,'POST',{body:message,internal});setMessage('')})}>Enviar / registar</button></div>:<div className={styles.meta}>Selecione um ticket.</div>}</section>
  </div>
 </div>
}
function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className={styles.field}><label>{label}</label><input value={value} onChange={e=>onChange(e.target.value)}/></div>}
function Textarea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className={styles.field}><label>{label}</label><textarea value={value} onChange={e=>onChange(e.target.value)}/></div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[any,any][]}){return <div className={styles.field}><label>{label}</label><select value={value} onChange={e=>onChange(e.target.value)}><option value="">— selecionar —</option>{options.map(([v,l])=><option key={String(v)} value={String(v)}>{String(l)}</option>)}</select></div>}
